debug: false
use-permissions: false
messages:
  no-permission: "Sorry, you don't have permission to create an Autocrafter of that type."
world-selection: blacklist
world-list: []
recipe-selection: blacklist
recipe-list: []
